### ISSUE TITLE
Preview API

### ISSUE THREAD

**Issue by olliekav** [javaporter/mm4-contentful#1]
This is not really an issue but I can't get my head around how to use the Preview API with Middleman and Contentful and wondered how you had it set up?

I have 'use_preview_api' set to true on staging version of the site hosted on Netlify, and I'm assuming I set up a web hook to auto deploy the draft but if it takes upto 5min every time it deploys how can I set the web hook to happen on auto save? It will just keep trying to deploy. That's also super confusing for the client as there is now way to preview content instantly.

**Comment by wanderingcrow** [comment]
I'm so sorry it took me so long to see this. I'm sure you've figured it out already, but it's a good question. In case other people have the same question: 

1-5 minutes is kind of what I'm seeing too. Sometimes it's a bit faster, but what I've also noticed is that if you have a draft in Contentful where required fields are not set, it can cause issues with the preview version (even though it's fine to have a draft without the required fields filled out). 

Part of what I'm trying to train my clients to understand though is that Contentful is not a WYSIWYG (and that's a good thing). Content is not design. I know it's helpful in situations, and I'm not knocking it by any stretch, but for what it's worth...

Also, the middleman-contentful folks are sooo helpful. I'll try to watch this repo better, but if I don't answer, they're a much better resource.
